version: '3.1'

volumes:
  pg_rails:

services:
  pg_db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=rails
      - POSTGRES_USER=rails
      - POSTGRES_DB=rails
 #   volumes:
 #    - pg_rails:volumes/postgres/data
    volumes:
      - pg_rails:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
#  app:
#    build:
#      context: ../.
#      dockerfile: docker/.Dockerfile
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
#    volumes:
#      - ../.:/myapp
#    ports:
#      - "3000:3000"
#    depends_on:
#      - pg_db
#    environment:
#      - DB_USERNAME=rails
#      - DB_PASSWORD=rails
#      - DB_HOST=db
#      - DB_NAME=vitaly_the_bot
#    container_name: app
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    restart: always
    ports:
      - "8080:8080"
