version: '3.1'

#volumes:
#  pg_rails:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=rails
      - POSTGRES_USER=rails
      - POSTGRES_DB=rails
 #   volumes:
 #    - pg_rails:volumes/postgres/data
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432